import { Section } from './types';

export const SECTIONS: Section[] = [
  {
    id: 1,
    title: '나 — 감정·성장·정체성',
    shortTitle: '나 자신',
    subtitle: '어떤 사람으로, 어떤 감각으로 살고 싶어?',
    color: '#7C6BAE',
    lightColor: '#EFEDF5',
    imageHintIntro: '이 느낌이 담긴 사진 3장을 찾아봐.',
    imageHints: ['"여유로운 아침"', '"혼자만의 시간"', '"나만의 루틴"'],
    situationChips: ['통창 있는 내 서재', '영어로 화상 미팅하는 나', '고객 후기가 쌓인 내 SNS', '내 이름이 담긴 웹사이트'],
    introText: '너 자신에 대해 이야기해보자. 지금의 나, 원하는 나를 같이 들여다볼게.',
    whyText: '비전보드에서 가장 먼저 들여다봐야 할 건 나 자신이야. 어떤 사람으로 살고 싶은지 알아야 나머지 이야기도 선명해지거든.',
    phaseOneQuestions: [
      {
        key: 'current',
        label: '지금',
        cushionText: '나는 네가 지금 어떻게 살고 있는지 궁금해.',
        questionText: '지금 너는 어떤 사람으로 살고 있어? 한 문장으로 말해줄래?',
        placeholder: '솔직한 게 제일 좋아.',
      },
      {
        key: 'want',
        label: '원해',
        cushionText: '이번엔 진짜 원하는 게 뭔지 물어볼게.',
        questionText: '나를 위해 언젠가 해보고 싶은 것, 되고 싶은 게 있어?',
        placeholder: '크든 작든 다 괜찮아.',
      },
      {
        key: 'feeling',
        label: '더 들여다보기',
        cushionText: '그게 이뤄졌을 때를 한번 상상해봐.',
        questionText: '그게 이뤄진 나는 어떤 기분으로 살고 있을 것 같아?',
        placeholder: '느낌이든, 상태든, 한 단어든 좋아.',
      },
      {
        key: 'keyword',
        label: '방향 키워드',
        cushionText: '마지막 질문이야.',
        questionText: '3년 뒤의 나를 한 단어로 표현해봐.',
        placeholder: '단어도, 짧은 표현도 좋아.',
      },
    ],
    reviewTemplate: '{name}{eun} 지금 {current}. 언젠가 {want}를 해보고 싶고, 그게 이뤄지면 {feeling}. 3년 뒤엔 \'{keyword}\'.',
    slots: [
      {
        id: 1,
        phase: 1,
        mainQuestion: '지금 나는 어떤 삶을 살고 있어? 한 문장으로.',
        placeholder: '좋은 답 나쁜 답 없어. 솔직한 게 제일 좋아.',
        example: '몸과 마음을 챙기며 나를 표현하는 연습을 하는 사람 / 열심히 사는데 방향이 아직 안 보이는 사람 / 하루하루 버티면서도 뭔가 쌓아가고 있는 사람',
        helpQuestions: [
          { id: 1, text: '요즘 아침에 일어날 때 가장 먼저 드는 감정이 뭐야?' },
          { id: 2, text: '지금 내 삶에서 가장 많은 에너지를 쓰는 게 뭐야?' },
          { id: 3, text: '주변 사람들이 나를 어떻게 보는 것 같아? 그게 맞는 것 같아?' },
        ],
      },
      {
        id: 2,
        phase: 1,
        mainQuestion: '3년 뒤의 나를 한 단어 (또는 짧은 표현)로 써봐.',
        placeholder: '목표가 아니어도 좋아. 어떤 느낌이나 상태면 돼.',
        example: '여유로운 / 단단한 / 설레는 / 자유로운 / 단단하고 트임 / 내 페이스로 사는',
        helpQuestions: [
          { id: 1, text: '3년 뒤의 나, 아침에 일어났을 때 어떤 기분이었으면 해?' },
          { id: 2, text: '지금 가장 부러운 사람이 있어? 그 사람의 어떤 면이 부러워?' },
          { id: 3, text: '지금 제일 갖고 싶은 감각이 뭐야? (여유, 자신감, 편안함...)' },
        ],
      },
      {
        id: 3,
        phase: 1,
        mainQuestion: '나를 위해 언젠가 꼭 해보고 싶은 것, 되고 싶은 모습이 있어?',
        placeholder: '크든 작든 다 괜찮아. 생각나는 거 다 써봐.',
        example: '악기 하나 배우기 / 내 이름으로 뭔가 만들기 / 번아웃 없이 사는 것 / 혼자 해외여행 / 내 브랜드 갖기',
        helpQuestions: [
          { id: 1, text: '돈도 시간도 충분하다면 지금 당장 뭐 하고 싶어?' },
          { id: 2, text: '어릴 때 하고 싶었는데 못 한 게 있어?' },
          { id: 3, text: '남들 눈치 없이 나만을 위해 쓴다면, 시간을 어디에 써?' },
        ],
      },
      {
        id: 5,
        phase: 1,
        mainQuestion: '그게 이뤄진 나는 어떤 기분으로 하루를 살고 있을 것 같아? 그 느낌을 표현해봐.',
        placeholder: '기분이든, 상태든, 한 단어든 문장이든 좋아.',
        example: '충만한 / 편안한 / 나답다는 느낌 / 불안 없이 내 하루를 사는 것 / 하루가 내 것인 느낌',
        helpQuestions: [
          { id: 1, text: '아까 원하는 것으로 써준 것들이 다 이뤄졌어. 그날 아침, 뭐가 달라져 있을 것 같아?' },
          { id: 2, text: '지금 가장 \'나답지 않다\'는 느낌이 드는 게 뭐야?' },
          { id: 3, text: '진짜 원하는 게 이뤄졌을 때, 누구한테 제일 먼저 말하고 싶어?' },
        ],
      },
      {
        id: 4,
        phase: 3,
        mainQuestion: '방금 쓴 단어가 이루어진 나의 하루야. 어디서 뭘 하고 있어?',
        placeholder: '구체적일수록 좋아. 시간, 장소, 감각까지 담아봐.',
        example: '카페 창가에서 혼자 책 읽는 중 / 아무 계획 없는 주말 아침, 느긋하게 커피 마시며 / 내 브랜드 사람들이랑 한자리에 모인 날',
        helpQuestions: [
          { id: 1, text: '그 키워드가 느껴지는 딱 한 순간만 떠올려봐. 어디야?' },
          { id: 2, text: '그 하루에서 제일 좋은 시간대가 언제야? 아침? 저녁?' },
          { id: 3, text: '그날 네 옆에 있는 건 뭐야? 사람? 장소? 물건?' },
        ],
      },
      {
        id: 6,
        phase: 4,
        mainQuestion: '이 느낌이 담긴 사진 3장을 찾아봐.',
        placeholder: '',
        example: '',
        helpQuestions: [],
      },
    ],
  },
  {
    id: 2,
    title: '건강 — 몸·마음·에너지',
    subtitle: '어떤 몸으로, 어떤 에너지로 살고 싶어?',
    color: '#4F7A5F',
    lightColor: '#EAEFEC',
    imageHintIntro: '이 느낌이 담긴 사진 3장을 찾아봐.',
    imageHints: ['"서핑 라이프"', '"새벽 러닝"', '"활기찬 아침"'],
    situationChips: ['새벽 러닝 후 개운한 나', '주 3회 운동이 루틴인 일상', '활기찬 에너지로 하루를 시작', '몸이 가벼운 주말 아침'],
    introText: '이번엔 몸 이야기야. 몸, 마음, 에너지를 들여다보자.',
    whyText: '원하는 삶을 살려면 몸이 따라줘야 해. 지금 몸 상태를 솔직하게 들여다보는 것, 그게 시작이야.',
    phaseOneQuestions: [
      {
        key: 'current',
        label: '지금',
        cushionText: '지금 몸 상태가 어떤지 들어보고 싶어.',
        questionText: '지금 내 몸 상태는 어때? 한 문장으로 말해줄래?',
        placeholder: '솔직하게 써봐.',
      },
      {
        key: 'want',
        label: '원해',
        cushionText: '몸에 관해 해보고 싶은 게 있어?',
        questionText: '해보고 싶은 운동, 도전하고 싶은 것, 몸에 관해 이루고 싶은 것.',
        placeholder: '거창하지 않아도 돼.',
      },
      {
        key: 'feeling',
        label: '더 들여다보기',
        cushionText: '몸이 가볍고 에너지 넘치는 날을 상상해봐.',
        questionText: '그때 하고 싶어지는 게 뭐야?',
        placeholder: '뭐든 좋아.',
      },
      {
        key: 'keyword',
        label: '방향 키워드',
        cushionText: '마지막 질문이야.',
        questionText: '3년 뒤 내 몸과의 관계를 한 단어로 표현해봐.',
        placeholder: '어떤 관계로 살고 싶어?',
      },
    ],
    reviewTemplate: '지금 몸은 {current}. 언젠가 {want}를 해보고 싶고, 몸이 가벼워지면 {feeling}. 3년 뒤 몸과의 관계는 \'{keyword}\'.',
    slots: [
      {
        id: 1,
        phase: 1,
        mainQuestion: '지금 내 몸 상태, 10점 만점에 몇 점? 그 점수인 이유는 뭐야?',
        placeholder: '숫자 + 한 줄이면 충분해.',
        example: '8점 — 꾸준히 운동 중인데 잠이 부족해 / 5점 — 유지는 되는데 뭔가 찜찜해 / 4점 — 항상 피곤하고 운동을 못 하고 있어',
        helpQuestions: [
          { id: 1, text: '요즘 하루 중 몸이 제일 힘든 시간이 언제야?' },
          { id: 2, text: '수면은 어때? 자고 나도 피곤해?' },
          { id: 3, text: '몸에 관해 지금 제일 신경 쓰이는 게 하나만 있다면?' },
        ],
      },
      {
        id: 2,
        phase: 1,
        mainQuestion: '3년 뒤 내 몸과 나의 관계, 어떤 한 단어면 좋겠어?',
        placeholder: '몸과 어떤 관계로 살고 싶어?',
        example: '가벼운 / 활기찬 / 내 편인 / 편안한 / 가벼운 평안함',
        helpQuestions: [
          { id: 1, text: '몸이 \'좋다\' 싶었던 순간이 마지막으로 언제야? 그때 어땠어?' },
          { id: 2, text: '건강한 내가 됐을 때, 뭐가 제일 달라져 있을 것 같아?' },
          { id: 3, text: '지금 몸이 나한테 주는 가장 큰 불편함이 뭐야?' },
        ],
      },
      {
        id: 3,
        phase: 1,
        mainQuestion: '해보고 싶은 운동, 도전하고 싶은 것, 몸에 관해 이루고 싶은 것.',
        placeholder: '거창하지 않아도 돼. 생각나는 거 다 써봐.',
        example: '마라톤 완주 / 서핑 배우기 / 주 3회 운동 루틴 만들기 / 한 달 금주 / 10km 런닝 / 요가',
        helpQuestions: [
          { id: 1, text: '몸이 지금보다 가볍고 활기차다면, 바로 해보고 싶은 게 뭐야?' },
          { id: 2, text: '한번쯤 해보고 싶었는데 \'나는 못 할 것 같아서\' 미룬 운동이나 도전이 있어?' },
          { id: 3, text: '지금 몸이 나한테 제일 원하는 게 뭔 것 같아?' },
        ],
      },
      {
        id: 5,
        phase: 1,
        mainQuestion: '몸이 가뿐하고 에너지 넘칠 때, 지금은 못 하지만 하고 싶어지는 게 있어?',
        placeholder: '건강해서 뭘 하고 싶은지가 더 강한 동기가 돼.',
        example: '새벽 5시에 일어나서 달리고 싶어 / 좋아하는 사람들이랑 하루 종일 뛰어놀고 싶어 / 등산 가고 싶어',
        helpQuestions: [
          { id: 1, text: '에너지 넘치는 날이면 어디 가고 싶어?' },
          { id: 2, text: '지금 피곤해서 못 하고 있는 게 뭐야?' },
          { id: 3, text: '건강한 네 모습을 상상하면, 어떤 장면이 떠올라?' },
        ],
      },
      {
        id: 4,
        phase: 3,
        mainQuestion: '방금 쓴 단어가 이루어진 하루야. 어디서 뭘 하고 있어?',
        placeholder: '아주 소소한 장면도 좋아.',
        example: '산 정상에서 탁 트인 뷰를 보는 중 / 운동 끝내고 개운하게 샤워하는 중 / 자고 일어났을 때 몸이 가벼운 걸 느끼는 아침',
        helpQuestions: [
          { id: 1, text: '몸이 좋을 때 네 하루는 어떻게 시작돼?' },
          { id: 2, text: '그 키워드가 느껴지는 가장 작은 순간이 있다면?' },
          { id: 3, text: '몸이 \'내 편\'이라고 느끼는 상황이 언제야?' },
        ],
      },
      {
        id: 6,
        phase: 4,
        mainQuestion: '이 느낌이 담긴 사진 3장을 찾아봐.',
        placeholder: '',
        example: '',
        helpQuestions: [],
      },
    ],
  },
  {
    id: 3,
    title: '관계·가족 — 남편·가족·친구',
    subtitle: '소중한 사람들과 어떤 시간을 나누고 싶어?',
    color: '#A8722A',
    lightColor: '#F5EFE5',
    imageHintIntro: '이 느낌이 담긴 사진 3장을 찾아봐.',
    imageHints: ['"따뜻한 식탁"', '"커플 여행"', '"가족 나들이"'],
    situationChips: ['가족이 함께하는 저녁 식탁', '남편과 여행지에서 걷는 중', '친구와 카페에서 깊은 수다', '편하게 통화하는 일상'],
    introText: '이번엔 관계 이야기야. 소중한 사람들과의 시간을 들여다보자.',
    whyText: '삶에서 가장 많은 에너지를 주고받는 게 관계야. 어떤 사람들과 어떻게 지내고 싶은지, 같이 생각해보자.',
    phaseOneQuestions: [
      {
        key: 'current',
        label: '지금',
        cushionText: '소중한 사람들 이야기를 들어볼게.',
        questionText: '10년 뒤, 소중한 사람이 나를 떠올릴 때 어떤 사람으로 기억됐으면 좋겠어?',
        placeholder: '거창하지 않아도 돼.',
      },
      {
        key: 'want',
        label: '원해',
        cushionText: '관계에서 꼭 이루고 싶은 게 있어?',
        questionText: '관계나 가족에 관해 꼭 이루고 싶은 것, 함께하고 싶은 것.',
        placeholder: '소소한 것도 좋아.',
      },
      {
        key: 'feeling',
        label: '더 들여다보기',
        cushionText: '가장 소중한 사람 이야기를 해봐.',
        questionText: '지금 가장 소중한데 더 가까워지고 싶은 사람이 있어? 그 사람과 어떤 시간을 보내고 싶어?',
        placeholder: '한 명이어도, 여러 명이어도 좋아.',
      },
      {
        key: 'keyword',
        label: '방향 키워드',
        cushionText: '원하는 관계를 한 단어로 담는다면.',
        questionText: '내가 원하는 관계의 느낌, 한 단어로 뽑아봐.',
        placeholder: '따뜻한, 든든한, 편안한...',
      },
    ],
    reviewTemplate: '{name}{eun} 소중한 사람에게 {current}으로 기억되고 싶어. 그러면서 {want}를 이루고 싶고, {feeling}. 원하는 관계의 느낌은 \'{keyword}\'.',
    slots: [
      {
        id: 1,
        phase: 1,
        mainQuestion: '10년 뒤, 소중한 사람이 나를 떠올릴 때 어떤 사람으로 기억됐으면 좋겠어?',
        placeholder: '지금 내 모습을 떠올리며 써봐. 거창하지 않아도 돼.',
        example: '그냥 옆에 있으면 편한 사람 / 힘들 때 떠오르는 사람 / 진심으로 내 편 들어주는 사람',
        helpQuestions: [
          { id: 1, text: '지금 내 관계에서 가장 잘 되고 있다고 느끼는 게 뭐야?' },
          { id: 2, text: '반대로, 관계에서 지금 제일 아쉬운 게 있다면?' },
          { id: 3, text: '가장 오래 기억될 것 같은 내 모습이 지금 뭔 것 같아?' },
        ],
      },
      {
        id: 2,
        phase: 1,
        mainQuestion: '내가 원하는 관계의 느낌, 한 단어로 뽑아봐.',
        placeholder: '관계에서 느끼고 싶은 감각이나 분위기를 담아봐.',
        example: '따뜻한 / 든든한 / 편안한 / 교류하는 / 깊은',
        helpQuestions: [
          { id: 1, text: '지금 관계에서 제일 아쉬운 게 뭐야? 그 반대가 원하는 거야.' },
          { id: 2, text: '가장 편한 관계를 생각해봐. 거기서 어떤 느낌이 들어?' },
          { id: 3, text: '관계에서 지금 가장 원하는 게 깊이야, 넓이야, 아니면 편안함이야?' },
        ],
      },
      {
        id: 3,
        phase: 1,
        mainQuestion: '관계나 가족에 관해 꼭 이루고 싶은 것, 함께하고 싶은 것이 있어?',
        placeholder: '소소한 것도 좋아. 생각나는 거 다 써봐.',
        example: '가족 해외여행 / 아이 갖기 / 반려동물 함께 키우기 / 매주 데이트하는 날 만들기 / 우리만의 공간',
        helpQuestions: [
          { id: 1, text: '지금 가장 소중한 사람과 꼭 해보고 싶은 게 뭐야?' },
          { id: 2, text: '가족 또는 가까운 사람들이랑 \'이건 꼭 하고 싶다\' 싶은 게 있어?' },
          { id: 3, text: '관계에서 지금 부족하다고 느끼는 게 채워진다면, 어떤 모습이야?' },
        ],
      },
      {
        id: 5,
        phase: 1,
        mainQuestion: '지금 가장 소중한데 더 가까워지고 싶은 사람이 있어? 그 사람이랑 어떤 시간을 보내고 싶어?',
        placeholder: '한 명이어도, 여러 명이어도 좋아.',
        example: '남편이랑 그냥 같이 있는 시간 / 오랜 친구랑 밥 먹으면서 속 얘기 / 언니랑 편하게 웃는 시간',
        helpQuestions: [
          { id: 1, text: '요즘 연락이 뜸해졌는데 보고 싶은 사람 있어?' },
          { id: 2, text: '지금 관계에서 \'이 사람이랑 이런 시간을 갖고 싶다\'는 게 있어?' },
          { id: 3, text: '더 가까워지고 싶은 사람에게 지금 하지 못하는 말이 있다면?' },
        ],
      },
      {
        id: 4,
        phase: 3,
        mainQuestion: '방금 쓴 단어가 이루어진 관계의 장면이야. 누구랑, 어디서?',
        placeholder: '특별한 날이 아니어도 괜찮아.',
        example: '여름 저녁 가족이 다 같이 밥 먹는 식탁 / 남편이랑 여행지에서 아무 말 없이 걷는 중 / 친구랑 카페에서 수다 떠는 중',
        helpQuestions: [
          { id: 1, text: '그 키워드가 느껴지는 가장 작은 순간이 뭐야?' },
          { id: 2, text: '지금까지 관계에서 가장 좋았던 순간이 언제야? 거기서 뭘 하고 있었어?' },
          { id: 3, text: '3년 뒤 나를 둘러싼 사람들과의 장면을 상상하면 어떤 모습이야?' },
        ],
      },
      {
        id: 6,
        phase: 4,
        mainQuestion: '이 느낌이 담긴 사진 3장을 찾아봐.',
        placeholder: '',
        example: '',
        helpQuestions: [],
      },
    ],
  },
  {
    id: 4,
    title: '일·성장 — 커리어·배움·의미',
    subtitle: '어떤 일로 배우며 성장하고 싶어?',
    color: '#5577A8',
    lightColor: '#EBEFF5',
    imageHintIntro: '이 느낌이 담긴 사진 3장을 찾아봐.',
    imageHints: ['"재택근무 라이프"', '"카페 작업"', '"내 브랜드"'],
    situationChips: ['내 브랜드 웹사이트', '고객 의뢰 이메일이 오는 아침', '재택으로 집중 작업하는 오후', '강의 또는 프로젝트 후기'],
    introText: '이번엔 일 이야기야. 커리어, 배움, 의미를 들여다보자.',
    whyText: '하루의 많은 시간을 일에 써. 그 시간이 어떻게 느껴지는지가 삶 전체에 영향을 주거든.',
    phaseOneQuestions: [
      {
        key: 'current',
        label: '지금',
        cushionText: '지금 일에 대한 이야기를 들어볼게.',
        questionText: '지금 일에서 제일 아쉬운 게 뭐야? 딱 하나만 말해줄래?',
        placeholder: '불만이어도 괜찮아. 솔직하게.',
      },
      {
        key: 'want',
        label: '원해',
        cushionText: '일이나 성장에 관한 버킷리스트가 있어?',
        questionText: '해보고 싶은 일, 이루고 싶은 것.',
        placeholder: '현실 가능 여부는 생각하지 말고.',
      },
      {
        key: 'feeling',
        label: '더 들여다보기',
        cushionText: '월요일 아침을 상상해봐.',
        questionText: '살짝이라도 기대되는 날이 있다면 — 어떤 일을 하고 있어?',
        placeholder: '지금 일이 싫다면, 어떤 일이라면 덜 싫을 것 같아?',
      },
      {
        key: 'keyword',
        label: '방향 키워드',
        cushionText: '일하는 나를 담는다면.',
        questionText: '어떤 사람으로 일하고 싶어? 한 단어나 한 문장으로.',
        placeholder: '단어도, 짧은 문장도 좋아.',
      },
    ],
    reviewTemplate: '지금 일에서 아쉬운 건 {current}. 언젠가 {want}를 해보고 싶고, {feeling}. 일하는 나를 표현하면 \'{keyword}\'.',
    slots: [
      {
        id: 1,
        phase: 1,
        mainQuestion: '지금 일에서 제일 아쉬운 게 뭐야? 딱 하나만.',
        placeholder: '불만이어도 괜찮아. 솔직하게.',
        example: '좋아하는 일인데 번아웃이 올 것 같아 / 성장하는 느낌이 없어 / 일 자체는 괜찮은데 환경이 아쉬워 / 의미를 못 느끼겠어',
        helpQuestions: [
          { id: 1, text: '지금 일에서 에너지 빠지는 순간이 언제야?' },
          { id: 2, text: '지금 일을 이대로 5년 더 한다고 상상하면 어때?' },
          { id: 3, text: '일 말고 나를 성장하게 만드는 게 있어? 그게 일에서는 왜 안 되는 것 같아?' },
        ],
      },
      {
        id: 2,
        phase: 1,
        mainQuestion: '일하는 나를 한 문장 (또는 단어)으로 써봐. 어떤 사람으로 일하고 싶어?',
        placeholder: '단어도 좋고, 짧은 문장도 좋아.',
        example: '내가 좋아하는 걸 하면서 돈도 버는 사람 / 성장하고 있다는 게 느껴지는 사람 / 내 안에 있는 걸 꺼내며 사는 사람',
        helpQuestions: [
          { id: 1, text: '이상적인 하루 일과를 상상하면, 어떤 일을 하고 있어?' },
          { id: 2, text: '일에서 \'이거다!\' 싶었던 순간이 있었어? 그때 뭘 하고 있었어?' },
          { id: 3, text: '내가 잘하면서 좋아하는 것, 딱 하나만 꼽으면?' },
        ],
      },
      {
        id: 3,
        phase: 1,
        mainQuestion: '일이나 성장에 관한 버킷리스트가 있어? 해보고 싶은 일, 이루고 싶은 것.',
        placeholder: '현실 가능 여부는 생각하지 말고 써봐.',
        example: '내 사업 시작하기 / 자격증 따기 / 강의 해보기 / 원하는 회사로 이직 / 내 프로그램 운영 / 브랜드 상업화',
        helpQuestions: [
          { id: 1, text: '지금 하고 있는 일 말고, 언젠가 꼭 해보고 싶은 일이 있어?' },
          { id: 2, text: '내 이름이 박힌 뭔가를 만든다면 뭐가 있을 것 같아?' },
          { id: 3, text: '성장에서 지금 제일 채우고 싶은 게 뭐야? 실력? 경험? 자신감?' },
        ],
      },
      {
        id: 5,
        phase: 1,
        mainQuestion: '월요일 아침, 살짝이라도 기대되는 날이 있다면 — 어떤 일을 하고 있어?',
        placeholder: '지금 일이 싫다면: 어떤 일이라면 월요일이 조금 덜 싫을 것 같아?',
        example: '내가 만든 것에 누군가 반응하는 것 기다리는 날 / 좋아하는 사람들이랑 함께 일하는 날 / 당당하게 제안 메일 보내는 날',
        helpQuestions: [
          { id: 1, text: '일하면서 \'시간 가는 줄 몰랐다\'는 경험이 마지막으로 언제야?' },
          { id: 2, text: '지금 일에서 그나마 즐거운 순간이 있어?' },
          { id: 3, text: '앞으로 5년 뒤 나는 어디서 뭘 하고 있으면 좋겠어?' },
        ],
      },
      {
        id: 4,
        phase: 3,
        mainQuestion: '방금 쓴 단어가 이루어진 날의 하루 마무리야. 어디야? 어떤 기분이야?',
        placeholder: '하루를 마치는 그 순간을 구체적으로 묘사해봐.',
        example: '내가 만든 것에 누군가 반응하는 순간 / 할 일 다 끝내고 가볍게 퇴근하는 길 / 재택에서 마지막 메일 보내고 노트북 닫는 순간',
        helpQuestions: [
          { id: 1, text: '일이 잘 됐다 싶은 날, 어떻게 하루가 끝나?' },
          { id: 2, text: '그 문장 속의 내가 일을 마치고 가장 먼저 하는 게 뭐야?' },
          { id: 3, text: '성취감이 느껴지는 순간을 상상하면 어디야?' },
        ],
      },
      {
        id: 6,
        phase: 4,
        mainQuestion: '이 느낌이 담긴 사진 3장을 찾아봐.',
        placeholder: '',
        example: '',
        helpQuestions: [],
      },
    ],
  },
  {
    id: 5,
    title: '돈·생활 — 재정·소비·여유',
    subtitle: '여유로운 상태에서 어떤 선택을 하고 싶어?',
    color: '#B05A36',
    lightColor: '#F5EBE7',
    imageHintIntro: '이 느낌이 담긴 사진 3장을 찾아봐.',
    imageHints: ['"여유로운 일상"', '"내 집 마련"', '"여행의 설렘"'],
    situationChips: ['망설임 없이 항공권을 결제하는 나', '부모님과 좋은 식당에서 밥 먹는 중', '원하는 물건을 고민 없이 담는 순간', '여유롭게 다음 여행을 계획 중'],
    introText: '이번엔 돈 이야기야. 여유, 자유, 선택을 들여다보자.',
    whyText: '돈은 액수가 아니라 어떤 선택을 하게 해주는지야. 어떤 자유를 원하는지 같이 들여다보자.',
    phaseOneQuestions: [
      {
        key: 'current',
        label: '지금',
        cushionText: '지금 돈 때문에 못 하고 있는 게 있어?',
        questionText: '지금 돈 때문에 참고 있거나 못 하고 있는 게 있어? 솔직하게.',
        placeholder: '부끄럽지 않아. 솔직한 게 제일 좋아.',
      },
      {
        key: 'want',
        label: '원해',
        cushionText: '돈 버킷리스트가 있어?',
        questionText: '사고 싶은 것, 가고 싶은 곳, 해주고 싶은 것.',
        placeholder: '크든 작든, 거창하든 소소하든 다 써봐.',
      },
      {
        key: 'feeling',
        label: '더 들여다보기',
        cushionText: '돈 걱정이 딱 사라진다면.',
        questionText: '이번 주를 어떻게 보내고 싶어?',
        placeholder: '꼭 비싼 게 아니어도 괜찮아.',
      },
      {
        key: 'keyword',
        label: '방향 키워드',
        cushionText: '돈이 충분할 때 느끼고 싶은 감정이 뭐야?',
        questionText: '한 단어로 표현해봐.',
        placeholder: '자유, 안정, 여유...',
      },
    ],
    reviewTemplate: '지금 돈 때문에 {current}를 못 하고 있어. 언젠가 {want}를 하고 싶고, 여유가 생기면 {feeling}. 돈이 충분할 때 느끼고 싶은 건 \'{keyword}\'.',
    slots: [
      {
        id: 1,
        phase: 1,
        mainQuestion: '지금 돈 때문에 참고 있거나 못 하고 있는 게 있어? 솔직하게.',
        placeholder: '부끄럽지 않아. 솔직한 게 제일 좋아.',
        example: '여행 / 좋아하는 취미 / 부모님 용돈 / 집 바꾸기 / 하고 싶은 공부 / 요가 등록',
        helpQuestions: [
          { id: 1, text: '요즘 가장 자주 \'돈 있으면 할 텐데...\' 하는 생각이 뭐야?' },
          { id: 2, text: '돈 때문에 포기한 게 최근에 뭐야?' },
          { id: 3, text: '지금 돈이 주는 가장 큰 불편함이나 스트레스가 뭐야?' },
        ],
      },
      {
        id: 2,
        phase: 1,
        mainQuestion: '돈이 충분할 때 느끼고 싶은 감정, 한 단어로.',
        placeholder: '액수보다 어떤 감각을 원하는지가 더 중요해.',
        example: '자유 / 안정 / 여유 / 당당함 / 든든함',
        helpQuestions: [
          { id: 1, text: '돈 걱정이 없는 날 아침은 어떤 기분일 것 같아?' },
          { id: 2, text: '돈이 충분했던 날 또는 기간이 있었어? 그때 느낌이 어땠어?' },
          { id: 3, text: '돈에서 지금 가장 원하는 게 안정이야, 자유야, 아니면 다른 거야?' },
        ],
      },
      {
        id: 3,
        phase: 1,
        mainQuestion: '돈 버킷리스트가 있어? 사고 싶은 것, 가고 싶은 곳, 해주고 싶은 것.',
        placeholder: '크든 작든, 거창하든 소소하든 다 써봐.',
        example: '하와이 여행 / 내 집 마련 / 차 바꾸기 / 부모님 여행 보내드리기 / 한 달 살기 / 해외 경험',
        helpQuestions: [
          { id: 1, text: '지금 당장 100만원이 생긴다면 뭐 하고 싶어?' },
          { id: 2, text: '언젠가 꼭 가보고 싶은 곳이나 해보고 싶은 경험이 있어?' },
          { id: 3, text: '나를 위해 써보고 싶은 것 중에 \'사치 같아서\' 미루고 있는 게 있어?' },
        ],
      },
      {
        id: 5,
        phase: 1,
        mainQuestion: '돈 걱정이 딱 사라진다면, 이번 주를 어떻게 보내고 싶어?',
        placeholder: '꼭 비싼 게 아니어도 괜찮아. 그냥 솔직하게.',
        example: '집안 물건 싹 바꾸기 / 요가 등록하기 / 오랫동안 미뤄온 여행 예약하기 / 그냥 아무것도 안 하기',
        helpQuestions: [
          { id: 1, text: '돈 걱정 없이 이번 주를 보낸다면, 하루를 어떻게 시작하고 싶어?' },
          { id: 2, text: '지금 돈이 없어서 못 하는 것 중에 실은 제일 하고 싶은 게 뭐야?' },
          { id: 3, text: '경제적으로 자유롭다면 일은 어떻게 달라져 있을 것 같아?' },
        ],
      },
      {
        id: 4,
        phase: 3,
        mainQuestion: '방금 쓴 단어가 이루어진 순간이야. 어떤 상황에 있어?',
        placeholder: '큰 이벤트가 아니어도 좋아. 작은 일상의 순간도.',
        example: '망설임 없이 항공권 끊는 중 / 부모님이랑 좋은 식당에서 밥 먹는 중 / 갖고 싶었던 걸 망설임 없이 사는 순간',
        helpQuestions: [
          { id: 1, text: '그 키워드가 느껴지는 가장 소소한 순간은 뭐야?' },
          { id: 2, text: '돈에 대해 \'이 정도면 충분하다\'는 감각이 느껴지는 장면을 상상해봐.' },
          { id: 3, text: '그 순간 네 표정이 어떨 것 같아?' },
        ],
      },
      {
        id: 6,
        phase: 4,
        mainQuestion: '이 느낌이 담긴 사진 3장을 찾아봐.',
        placeholder: '',
        example: '',
        helpQuestions: [],
      },
    ],
  },
  {
    id: 6,
    title: '공간·환경 — 집·동네·일상의 배경',
    subtitle: '매일 돌아오고 싶은 공간은 어떤 모습이야?',
    color: '#3E7E8A',
    lightColor: '#E8F0F1',
    imageHintIntro: '이 느낌이 담긴 사진 3장을 찾아봐.',
    imageHints: ['"감성 인테리어"', '"나만의 서재"', '"포근한 집"'],
    situationChips: ['창가에서 커피 마시며 시작하는 아침', '서재에서 나만의 시간', '마당이나 테라스에서 보내는 저녁', '정돈된 공간에서의 주말'],
    introText: '이번엔 공간 이야기야. 집, 동네, 일상의 배경을 들여다보자.',
    whyText: '매일 돌아오는 공간이 어떤 느낌이냐가 생각보다 삶에 큰 영향을 줘. 어떤 공간에서 살고 싶어?',
    phaseOneQuestions: [
      {
        key: 'current',
        label: '지금',
        cushionText: '지금 집 이야기를 들어볼게.',
        questionText: '집에 돌아왔을 때 제일 먼저 하고 싶은 게 뭐야? 지금 그게 가능해?',
        placeholder: '현재 집의 현실을 솔직하게 써봐.',
      },
      {
        key: 'want',
        label: '원해',
        cushionText: '살고 싶은 공간, 갖고 싶은 환경이 있어?',
        questionText: '살고 싶은 곳, 갖고 싶은 공간, 해보고 싶은 것.',
        placeholder: '크든 작든 다 괜찮아.',
      },
      {
        key: 'feeling',
        label: '더 들여다보기',
        cushionText: '이상적인 집에서 하루를 보낸다면.',
        questionText: '아침부터 저녁까지 어떻게 흘러가?',
        placeholder: '시간 순서대로 써봐.',
      },
      {
        key: 'keyword',
        label: '방향 키워드',
        cushionText: '원하는 공간을 한 단어로 담는다면.',
        questionText: '내가 원하는 공간을 딱 한 단어로 표현하면?',
        placeholder: '따뜻한, 조용한, 나다운...',
      },
    ],
    reviewTemplate: '지금은 {current}. 언젠가 {want}를 이루고 싶고, 이상적인 공간에서는 {feeling}. 원하는 공간을 한 단어로 하면 \'{keyword}\'.',
    slots: [
      {
        id: 1,
        phase: 1,
        mainQuestion: '집에 돌아왔을 때 제일 먼저 하고 싶은 게 뭐야? 지금 그게 가능해?',
        placeholder: '현재 집의 현실을 솔직하게 써봐.',
        example: '창가에서 커피 마시고 싶은데 딱 맞는 자리가 없어 / 지금도 정돈된 곳에 앉아서 쉬는 게 좋아 / 좋은데 내 공간이 없어서 아쉬워',
        helpQuestions: [
          { id: 1, text: '지금 집에서 가장 좋아하는 공간은 어디야? 왜?' },
          { id: 2, text: '집에서 제일 불편한 게 뭐야?' },
          { id: 3, text: '요즘 집에서 가장 많은 시간을 보내는 곳이 어디야? 그게 좋아?' },
        ],
      },
      {
        id: 2,
        phase: 1,
        mainQuestion: '내가 원하는 공간을 딱 한 단어로 표현하면?',
        placeholder: '공간에서 느끼고 싶은 감각을 담아봐.',
        example: '따뜻한 / 조용한 / 나다운 / 포근한 / 심플한',
        helpQuestions: [
          { id: 1, text: '가장 편안하게 쉬었던 공간이 어디야? 거기서 어떤 느낌이 들었어?' },
          { id: 2, text: '카페, 친구 집, 여행지 중에서 가장 오래 있고 싶었던 공간이 있어?' },
          { id: 3, text: '집에서 \'이것만 바뀌어도 좋겠다\'는 게 있어?' },
        ],
      },
      {
        id: 3,
        phase: 1,
        mainQuestion: '살고 싶은 곳, 갖고 싶은 공간, 해보고 싶은 것.',
        placeholder: '크든 작든 다 괜찮아. 생각나는 거 다 써봐.',
        example: '제주 한 달 살기 / 마당 있는 집 / 숲 view 아파트 / 내 서재 갖기 / 정돈된 집',
        helpQuestions: [
          { id: 1, text: '살고 싶은 집이 있다면 어디야? 어떤 모습이야?' },
          { id: 2, text: '지금 집에서 갖고 싶은 공간이 있어? (서재, 작업실, 넓은 욕실...)' },
          { id: 3, text: '어딘가에서 \'여기서 살고 싶다\' 싶었던 곳이 있어?' },
        ],
      },
      {
        id: 5,
        phase: 1,
        mainQuestion: '이상적인 집에서 하루를 보낸다면, 아침부터 저녁까지 어떻게 흘러가?',
        placeholder: '시간 순서대로 써봐. 소소할수록 좋아.',
        example: '숲 view 보며 스트레칭·명상 → 간단한 아침 → 서재에서 작업 → 제대로 요리 → 아로마 켜고 폭 잠',
        helpQuestions: [
          { id: 1, text: '이상적인 아침이 있다면 어떻게 시작해?' },
          { id: 2, text: '집에서 제일 오래 있고 싶은 공간은 어디야? 거기서 뭘 해?' },
          { id: 3, text: '집에서 보내는 저녁 시간이 어떠면 좋겠어?' },
        ],
      },
      {
        id: 4,
        phase: 3,
        mainQuestion: '방금 쓴 단어가 이루어진 공간이야. 거기서 뭘 하고 있어?',
        placeholder: '구체적인 장면을 묘사해봐.',
        example: '소파에 누워 좋아하는 거 틀어놓기 / 넓은 주방에서 주말 아침 요리하기 / 서재에서 내 생각 정리하고 세상에 펼쳐놓기',
        helpQuestions: [
          { id: 1, text: '그 공간에서 뭘 할 때 가장 행복해?' },
          { id: 2, text: '지금 집에서 가장 자주 하는 것 vs 이상적인 집에서 하고 싶은 것이 달라?' },
          { id: 3, text: '그 공간에서의 하루를 한 문장으로 표현하면?' },
        ],
      },
      {
        id: 6,
        phase: 4,
        mainQuestion: '이 느낌이 담긴 사진 3장을 찾아봐.',
        placeholder: '',
        example: '',
        helpQuestions: [],
      },
    ],
  },
];

export function getSection(id: number): Section | undefined {
  return SECTIONS.find((s) => s.id === id);
}
